package org.magcruise.citywalk.model.json;

import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;
import org.magcruise.citywalk.model.row.Entry;

import net.sf.persist.annotations.Column;

public class EntryJson {

	private String id;
	private String userId;
	private String courseId;
	private long createdAt;

	public EntryJson() {
	}

	public EntryJson(Entry e) {
		this.userId = e.getUserId();
		this.courseId = e.getCourseId();
		this.createdAt = e.getCreatedAt().getTime();
	}

	@Column(autoGenerated = true)
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String id) {
		this.userId = id;
	}

	public String getCourseId() {
		return courseId;
	}

	public void setCourseId(String groupId) {
		this.courseId = groupId;
	}

	@Override
	public String toString() {
		return ToStringBuilder.reflectionToString(this, ToStringStyle.SHORT_PREFIX_STYLE);
	}

	public long getCreatedAt() {
		return createdAt;
	}

	public void setCreatedAt(long createdAt) {
		this.createdAt = createdAt;
	}

}
