package org.magcruise.citywalk.model.row;

import java.util.Date;

import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;
import org.magcruise.citywalk.model.relation.BadgesTable;

import net.sf.persist.annotations.Column;
import net.sf.persist.annotations.Table;

@Table(name = BadgesTable.TABLE_NAME)
public class Badge {

	private long id;
	private Date createdAt;
	private String userId;
	private long badgeDefinitionId;

	public Badge() {

	}

	public Badge(String userId, long badgeDefinitionId) {
		this.userId = userId;
		this.badgeDefinitionId = badgeDefinitionId;
	}

	@Column(autoGenerated = true)
	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Override
	public String toString() {
		return ToStringBuilder.reflectionToString(this, ToStringStyle.SHORT_PREFIX_STYLE);
	}

	public Date getCreatedAt() {
		return createdAt;
	}

	public void setCreatedAt(Date created) {
		this.createdAt = created;
	}

	public long getBadgeDefinitionId() {
		return badgeDefinitionId;
	}

	public void setBadgeDefinitionId(long badgeId) {
		this.badgeDefinitionId = badgeId;
	}

}
