package org.magcruise.citywalk.model.row;

import java.util.Date;

import org.magcruise.citywalk.model.input.Input;
import org.magcruise.citywalk.model.json.ActivityJson;
import org.magcruise.citywalk.model.relation.SubmittedActivitiesTable;

import net.sf.persist.annotations.Column;
import net.sf.persist.annotations.Table;

@Table(name = SubmittedActivitiesTable.TABLE_NAME)
public class SubmittedActivity extends Activity {
	public SubmittedActivity() {
	}

	public SubmittedActivity(Date createdAt, String courseId, String userId, String checkpointId,
			double lat, double lon, String taskId, double score, Input input, String options) {
		super(createdAt, courseId, userId, checkpointId, lat, lon, taskId, score, input, options);
	}

	public SubmittedActivity(ActivityJson json) {
		super(json);
	}

	@Override
	@Column(autoGenerated = true)
	public long getId() {
		return super.getId();
	}

}
